export type OrderForm = {
  id: string | null;
  order_number?: string;
  sale_number?: string;
  purchase_number?: string;
  order_class?: string;
  order_category?: string;
  contact_id: string;
  store_id: string;
  inventory_id?: string;
  product_id?: string;
  quantity?: string;
  billing_address: string;
  shipping_address: string;
  status: string;
  option: string;
  stage: string;
  order_date: Date;
  expected_date?: Date;
  discount_type: string;
  discount: number;
  base_price: number;
  VAT: number;
  total_amount: number;
  delivery_status?: string;
  client_notes: string;
  support_file?: string;
  date_closed: Date | null;
  items?: any[];
};
