name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install 
      - name: Build
        run: npm run build
        env: 
          VITE_BASE_URL: ${{ secrets.STAGING_API_URL }}
          VITE_MK_URL: ${{ secrets.STAGING_MK_BASE_URL }}
          VITE_APP_URL: ${{ secrets.STAGING_APP_BASE_URL }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'do-known-hosts'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /var/www/vendor
            rm -rf ./*
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.USER }}@${{ secrets.IP_ADDRESS }}:/var/www/vendor/

           
